# Generated by Django 4.0 on 2021-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_fileupload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='', upload_to='Doc/'),
            preserve_default=False,
        ),
    ]
